version: '3.8'

services:
  jellyfin-playlist-manager:
    image: mrorbitman/jellyfin-playlist-manager:latest
    ports:
      - "3000:3000"
    environment:
      # AWS Configuration for AI Suggestions
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      
      # Jellyfin Configuration
      - JELLYFIN_SERVER_URL=${JELLYFIN_SERVER_URL:-http://jellyfin:8096}
      
      # Download Configuration
      - MUSIC_DOWNLOAD_DIR=/app/downloads
      - YT_DLP_PATH=/usr/bin/yt-dlp
      - COOKIES_PATH=/app/data/cookies.txt
      
      # Next.js Configuration
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    
    volumes:
      # Mount your music directory (adjust path as needed)
      - ${MUSIC_DOWNLOAD_DIR:-./downloads}:/app/downloads
      # Mount directory for cookies and other data
      - ${DATA_DIR:-./data}:/app/data
    
    restart: unless-stopped
    
    # Optional: connect to Jellyfin network if running Jellyfin in Docker
    # networks:
    #   - jellyfin-network

# Optional: create network for Jellyfin integration
# networks:
#   jellyfin-network:
#     external: true
